server:
  listen_addr: "127.0.0.1:8080"
  workers: 4

proxy:
  connection_timeout: "30s"
  request_timeout: "30s"
  max_connections: 1000
  enable_http2: true

backends:
  - name: "api1"
    url: "http://localhost:3000"
    weight: 1
    timeout: "5s"
    retry_attempts: 3
    health_check:
      enabled: true
      interval: "10s"
      path: "/health"
      timeout: "2s"
  
  - name: "api2"
    url: "http://localhost:3001"
    weight: 1
    timeout: "5s"
    retry_attempts: 3
    health_check:
      enabled: true
      interval: "10s"
      path: "/health"
      timeout: "2s"

plugins:
  enabled:
    - "rate-limiter"
  settings:
    rate-limiter:
      requests_per_second: 100 